MODELO BASICO

In [5]:
import numpy as np

# ============================================
#  Parámetros del modelo
# ============================================

Pi = 5.0      # tasa de producción de S
beta = 0.0095  # infección S→Z
delta = 0.0001   # transición S→R
zeta = 0.0001    # transición R→Z
alpha = 0.005 # término extra S→Z

# ============================================
#  Sistema de ecuaciones diferenciales
# ============================================

def f(t, y):
    S, Z, R = y
    dS = Pi - beta*S*Z - delta*S
    dZ = beta*S*Z + zeta*R - alpha*S*Z
    dR = delta*S + alpha*S*Z - zeta*R
    return np.array([dS, dZ, dR])


# ============================================
#  Métodos numéricos
# ============================================

def euler(f, y0, t):
    h = t[1] - t[0]
    Y = np.zeros((len(t), len(y0)))
    Y[0] = y0
    for i in range(len(t)-1):
        Y[i+1] = Y[i] + h * f(t[i], Y[i])
    return Y

def heun(f, y0, t):
    h = t[1] - t[0]
    Y = np.zeros((len(t), len(y0)))
    Y[0] = y0
    for i in range(len(t)-1):
        k1 = f(t[i], Y[i])
        k2 = f(t[i] + h, Y[i] + h*k1)
        Y[i+1] = Y[i] + 0.5*h*(k1 + k2)
    return Y

def rk4(f, y0, t):
    h = t[1] - t[0]
    Y = np.zeros((len(t), len(y0)))
    Y[0] = y0
    for i in range(len(t)-1):
        k1 = f(t[i], Y[i])
        k2 = f(t[i] + h/2, Y[i] + h*k1/2)
        k3 = f(t[i] + h/2, Y[i] + h*k2/2)
        k4 = f(t[i] + h, Y[i] + h*k3)
        Y[i+1] = Y[i] + (h/6)*(k1 + 2*k2 + 2*k3 + k4)
    return Y


# ============================================
#  Condiciones iniciales y tiempo
# ============================================

y0 = np.array([20, 5, 0])   # S(0), Z(0), R(0)
t = np.linspace(0, 50, 500) # de 0 a 50 con 500 puntos

# ============================================
#  Soluciones numéricas
# ============================================

Y_euler = euler(f, y0, t)
Y_heun  = heun(f, y0, t)
Y_rk4   = rk4(f, y0, t)

# ============================================
#  Impresión solucion
# ============================================

print("===== Euler =====")
print(Y_euler[-1])

print("\n===== Heun  =====")
print(Y_heun[-1])

print("\n===== RK4 =====")
print(Y_rk4[-1])

===== Euler =====
[  4.07093438 131.27399146 139.65507416]

===== Heun  =====
[  4.07104182 131.27498381 139.65397437]

===== RK4 =====
[  4.07103332 131.27498956 139.65397713]


Modelo con infeccion latente

In [7]:
import numpy as np

# ============================================
#  Parámetros del modelo SIZR
# ============================================

Pi = 5.0      # tasa de producción de S
beta = 0.0095  # infección S→Z
delta = 0.0001   # transición S→R
zeta = 0.0001    # transición R→Z
alpha = 0.005   # término extra S→Z
rho = 0.005     # progresión de I -> Z

# ============================================
#  Sistema SIZR
# ============================================

def f(t, y):
    S, I, Z, R = y

    dS = Pi - beta*S*Z - delta*S
    dI = beta*S*Z - rho*I - delta*I
    dZ = rho*I + zeta*R - alpha*S*Z
    dR = delta*S + delta*I + alpha*S*Z - zeta*R

    return np.array([dS, dI, dZ, dR])


# ============================================
#  Métodos numéricos
# ============================================

def euler(f, y0, t):
    h = t[1] - t[0]
    Y = np.zeros((len(t), len(y0)))
    Y[0] = y0
    for i in range(len(t)-1):
        Y[i+1] = Y[i] + h * f(t[i], Y[i])
    return Y


def heun(f, y0, t):
    h = t[1] - t[0]
    Y = np.zeros((len(t), len(y0)))
    Y[0] = y0
    for i in range(len(t)-1):
        k1 = f(t[i], Y[i])
        k2 = f(t[i] + h, Y[i] + h*k1)
        Y[i+1] = Y[i] + 0.5*h*(k1 + k2)
    return Y


def rk4(f, y0, t):
    h = t[1] - t[0]
    Y = np.zeros((len(t), len(y0)))
    Y[0] = y0
    for i in range(len(t)-1):
        k1 = f(t[i], Y[i])
        k2 = f(t[i] + h/2, Y[i] + h*k1/2)
        k3 = f(t[i] + h/2, Y[i] + h*k2/2)
        k4 = f(t[i] + h, Y[i] + h*k3)
        Y[i+1] = Y[i] + (h/6)*(k1 + 2*k2 + 2*k3 + k4)
    return Y


# ============================================
#  Condiciones iniciales y tiempo
# ============================================

y0 = np.array([20, 5, 2, 0])  # S(0), I(0), Z(0), R(0)
t = np.linspace(0, 60, 600)   # tiempo 0 a 60

# ============================================
#  Soluciones numéricas
# ============================================

Y_euler = euler(f, y0, t)
Y_heun  = heun(f, y0, t)
Y_rk4   = rk4(f, y0, t)

# ============================================
#  Impresión de la solucion
# ============================================

print("===== Euler  =====")
print(Y_euler[-1])

print("\n===== Heun =====")
print(Y_heun[-1])

print("\n===== RK4  =====")
print(Y_rk4[-1])

===== Euler  =====
[3.09833049e+02 1.12776077e+01 3.70463666e-02 5.85229702e+00]

===== Heun =====
[3.09828377e+02 1.12791379e+01 3.70526059e-02 5.85543274e+00]

===== RK4  =====
[3.09828371e+02 1.12791406e+01 3.70525776e-02 5.85543562e+00]


Modelo con cuarentena

In [8]:
import numpy as np

# ---------------------------
# Parámetros (ajusta a tu gusto)
# ---------------------------



Pi    = 5.0     # Π
beta  = 0.0095  # β
delta = 0.0001  # δ
rho = 0.005     # ρ
kappa = 0.05    # κ
zeta = 0.0001   # ζ
alpha = 0.005   # α
sigma = 0.02    # σ
gamma = 0.01    # γ

# ---------------------------
# Sistema S,I,Z,R,Q
# ---------------------------
def f(t, y):
    S, I, Z, R, Q = y
    dS = Pi - beta*S*Z - delta*S
    dI = beta*S*Z - rho*I - delta*I - kappa*I
    dZ = rho*I + zeta*R - alpha*S*Z - sigma*Z
    dR = delta*S + delta*I + alpha*S*Z - zeta*R + gamma*Q
    dQ = kappa*I + sigma*Z - gamma*Q
    return np.array([dS, dI, dZ, dR, dQ])

# ---------------------------
# Métodos numéricos
# ---------------------------
def euler(f, y0, t):
    h = t[1] - t[0]
    Y = np.zeros((len(t), len(y0)))
    Y[0] = y0
    for i in range(len(t)-1):
        Y[i+1] = Y[i] + h * f(t[i], Y[i])
    return Y

def heun(f, y0, t):
    h = t[1] - t[0]
    Y = np.zeros((len(t), len(y0)))
    Y[0] = y0
    for i in range(len(t)-1):
        k1 = f(t[i], Y[i])
        k2 = f(t[i] + h, Y[i] + h*k1)
        Y[i+1] = Y[i] + 0.5*h*(k1 + k2)
    return Y

def rk4(f, y0, t):
    h = t[1] - t[0]
    Y = np.zeros((len(t), len(y0)))
    Y[0] = y0
    for i in range(len(t)-1):
        k1 = f(t[i], Y[i])
        k2 = f(t[i] + h/2, Y[i] + h*k1/2)
        k3 = f(t[i] + h/2, Y[i] + h*k2/2)
        k4 = f(t[i] + h, Y[i] + h*k3)
        Y[i+1] = Y[i] + (h/6)*(k1 + 2*k2 + 2*k3 + k4)
    return Y

# ---------------------------
# Condiciones iniciales y tiempo
# ---------------------------
y0 = np.array([20.0, 5.0, 2.0, 0.0, 0.0])  # S(0), I(0), Z(0), R(0), Q(0)
t = np.linspace(0, 60, 601)               # 0..60 con paso 0.1

# ---------------------------
# Resolver
# ---------------------------
Y_euler = euler(f, y0, t)
Y_heun  = heun(f, y0, t)
Y_rk4   = rk4(f, y0, t)

# ---------------------------
# Imprimir (primeras y últimas filas)
# ---------------------------
np.set_printoptions(precision=5, suppress=True)

print("===== Euler  =====")
print(Y_euler[-1])

print("\n===== Heun =====")
print(Y_heun[-1])

print("\n===== RK4  =====")
print(Y_rk4[-1])

===== Euler  =====
[313.99163   0.63144   0.00247   6.48389   5.89057]

===== Heun =====
[313.98757   0.63489   0.00248   6.48697   5.88808]

===== RK4  =====
[313.98756   0.63489   0.00248   6.48698   5.88809]


Modelo con Tratamiento

In [9]:
import numpy as np

# ============================================
# Parámetros del modelo
# ============================================

Pi    = 5.0     # Π
beta  = 0.0095  # β
delta = 0.0001  # δ
rho = 0.005     # ρ
zeta = 0.0001   # ζ
alpha = 0.005   # α
c     = 0.05    # c   <-- aparece en S' y Z'

# ============================================
# Sistema diferencial S, I, Z, R
# ============================================

def f(t, y):
    S, I, Z, R = y

    dS = Pi - beta*S*Z - delta*S + c*Z
    dI = beta*S*Z - rho*I - delta*I
    dZ = rho*I + zeta*R - alpha*S*Z - c*Z
    dR = delta*S + delta*I + alpha*S*Z - zeta*R

    return np.array([dS, dI, dZ, dR])

# ============================================
# Métodos numéricos
# ============================================

def euler(f, y0, t):
    h = t[1] - t[0]
    Y = np.zeros((len(t), len(y0)))
    Y[0] = y0
    for i in range(len(t)-1):
        Y[i+1] = Y[i] + h * f(t[i], Y[i])
    return Y

def heun(f, y0, t):
    h = t[1] - t[0]
    Y = np.zeros((len(t), len(y0)))
    Y[0] = y0
    for i in range(len(t)-1):
        k1 = f(t[i], Y[i])
        k2 = f(t[i] + h, Y[i] + h*k1)
        Y[i+1] = Y[i] + 0.5*h*(k1 + k2)
    return Y

def rk4(f, y0, t):
    h = t[1] - t[0]
    Y = np.zeros((len(t), len(y0)))
    Y[0] = y0
    for i in range(len(t)-1):
        k1 = f(t[i], Y[i])
        k2 = f(t[i] + h/2, Y[i] + h*k1/2)
        k3 = f(t[i] + h/2, Y[i] + h*k2/2)
        k4 = f(t[i] + h, Y[i] + h*k3)
        Y[i+1] = Y[i] + (h/6)*(k1 + 2*k2 + 2*k3 + k4)
    return Y

# ============================================
# Condiciones iniciales y simulación
# ============================================

y0 = np.array([20.0, 5.0, 3.0, 0.0])   # S(0), I(0), Z(0), R(0)
t  = np.linspace(0, 60, 601)          # tiempo

# ============================================
# Soluciones numéricas
# ============================================

Y_euler = euler(f, y0, t)
Y_heun  = heun(f, y0, t)
Y_rk4   = rk4(f, y0, t)

# ============================================
# Impresión
# ============================================

np.set_printoptions(precision=5, suppress=True)


print("===== Euler  =====")
print(Y_euler[-1])

print("\n===== Heun =====")
print(Y_heun[-1])

print("\n===== RK4  =====")
print(Y_rk4[-1])

===== Euler  =====
[310.14159  11.67744   0.03712   6.14386]

===== Heun =====
[310.12043  11.68898   0.03716   6.15344]

===== RK4  =====
[310.12038  11.68901   0.03716   6.15346]
